import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "sonner";
import { ModalProvider } from '@/providers/modal-providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const session = auth();
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <ModalProvider/>
        {children}
        </body>
    </html>
    </SessionProvider>
  );
}
